[package]
name = "from_json_macros"
version = "0.0.1"
authors = ["Pierre Krieger <pierre.krieger1708@gmail.com>"]

[lib]
name = "from_json_macros"
path = "src/lib.rs"
plugin = true

[dev-dependencies.from_json]
path = ".."
